require "br_inscricao_estadual/version"
require "br_inscricao_estadual/common"
require "br_inscricao_estadual/base"
require "br_inscricao_estadual/ac"
require "br_inscricao_estadual/al"
require "br_inscricao_estadual/ap"
require "br_inscricao_estadual/am"
require "br_inscricao_estadual/ba"
require "br_inscricao_estadual/ba_8"
require "br_inscricao_estadual/ba_9"
require "br_inscricao_estadual/ce"
require "br_inscricao_estadual/df"
require "br_inscricao_estadual/es"
require "br_inscricao_estadual/go"
require "br_inscricao_estadual/ma"
require "br_inscricao_estadual/mt"
require "br_inscricao_estadual/ms"
require "br_inscricao_estadual/mg"
require "br_inscricao_estadual/pa"
require "br_inscricao_estadual/pb"
require "br_inscricao_estadual/pr"
require "br_inscricao_estadual/pe"
require "br_inscricao_estadual/pi"
require "br_inscricao_estadual/rj"
require "br_inscricao_estadual/rn"
require "br_inscricao_estadual/rn_9"
require "br_inscricao_estadual/rn_10"
require "br_inscricao_estadual/rs"
require "br_inscricao_estadual/ro"
require "br_inscricao_estadual/rr"
require "br_inscricao_estadual/sc"
require "br_inscricao_estadual/sp"
require "br_inscricao_estadual/sp_p"
require "br_inscricao_estadual/se"
require "br_inscricao_estadual/to"

module BrInscricaoEstadual
end



